/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ejercicio2.pkg2.Ejercicio22;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class VEventos extends javax.swing.JFrame {
    private char opcion;
    /**
     * Creates new form VPrincipal
     */
    public VEventos() {
        initComponents();
        opcion=Ejercicio22.opcion();
        try{    
            switch(opcion){
                case 'g':
                    bConfirmar.setVisible(false);
                    break;
                case 'e':
                    bAceptar.setEnabled(false);
                    tfLugar.setEnabled(false);
                    tfFecha.setEnabled(false);
                    tfHoraFin.setEnabled(false);
                    tfHoraInicio.setEnabled(false);
                    tfAforo.setEnabled(false);
                    break;
                case 'a':
                    bAceptar.setEnabled(false);
                    tfLugar.setEnabled(false);
                    tfFecha.setEnabled(false);
                    tfHoraFin.setEnabled(false);
                    tfHoraInicio.setEnabled(false);
                    tfAforo.setEnabled(false);
                    break;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfLugar = new javax.swing.JTextField();
        tfFecha = new javax.swing.JTextField();
        tfHoraInicio = new javax.swing.JTextField();
        tfHoraFin = new javax.swing.JTextField();
        tfAforo = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Información eventos");

        jLabel2.setText("Nombre");

        jLabel3.setText("Lugar");

        jLabel4.setText("Fecha");

        jLabel5.setText("Hora inicio");

        jLabel6.setText("Hora fin");

        jLabel7.setText("Numero de personas");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLugarActionPerformed(evt);
            }
        });

        tfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaActionPerformed(evt);
            }
        });

        tfHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraInicioActionPerformed(evt);
            }
        });

        tfHoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraFinActionPerformed(evt);
            }
        });

        tfAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAforoActionPerformed(evt);
            }
        });

        bAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bConfirmar)
                .addGap(32, 32, 32)
                .addComponent(bAceptar)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(tfHoraInicio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfHoraFin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfAforo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfNombre))
                    .addComponent(tfLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfHoraInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bConfirmar))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        try{
            Pattern p=Pattern.compile("^[a-zA-Z]{1,}$");
            Matcher m=p.matcher(tfNombre.getText());
            if(!m.matches())
                    throw new Exception("No puede estar vacio o contener numeros");
            tfLugar.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLugarActionPerformed
        try{
            Pattern p=Pattern.compile("^[0-9]*[a-zA-Z]{1,}[0-9]*$");
            Matcher m=p.matcher(tfLugar.getText());
            if(!m.matches())
                    throw new Exception("No puede estar vacio");
            tfFecha.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tfLugarActionPerformed

    private void tfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaActionPerformed
        try{
            Pattern p=Pattern.compile("^[1-9]{2}-[1-9]{2}-[0-9]{4}$");
            Matcher m=p.matcher(tfLugar.getText());
            if(!m.matches())
                    throw new Exception("tiene que tener este formato xx/xx/xxxx");
            tfHoraInicio.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tfFechaActionPerformed

    private void tfHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraInicioActionPerformed
           try{
            Pattern p=Pattern.compile("^[1-9]{2}:[1-9]{2}$");
            Matcher m=p.matcher(tfLugar.getText());
            if(!m.matches())
                    throw new Exception("tiene que tener este formato xx/xx/xxxx");
            tfHoraInicio.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tfHoraInicioActionPerformed

    private void tfHoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraFinActionPerformed
           try{
            Pattern p=Pattern.compile("^^[1-9]{2}:[1-9]{2}$");
            Matcher m=p.matcher(tfLugar.getText());
            if(!m.matches())
                    throw new Exception("tiene que tener este formato xx/xx/xxxx");
            tfHoraInicio.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tfHoraFinActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try{    
            switch(opcion){
                case 'g':
                    Ejercicio22.guardar(tfNombre.getText(),tfLugar.getText(),tfFecha.getText(),tfHoraInicio.getText(),tfHoraFin.getText(),tfAforo.getText());
                    Ejercicio22.inicio();
                    break;
                case 'e':
                    Ejercicio22.eliminar();
                    Ejercicio22.inicio();
                    break;
                case 'a':
                    Ejercicio22.actualizar(tfNombre.getText(),tfLugar.getText(),tfFecha.getText(),tfHoraInicio.getText(),tfHoraFin.getText(),tfAforo.getText());
                    Ejercicio22.inicio();
                    break;
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Problemas al hacer la acción a realizar");
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tfAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAforoActionPerformed
        
    }//GEN-LAST:event_tfAforoActionPerformed

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        bAceptar.setEnabled(true);
        try{    
            switch(opcion){
                case 'e':
                    Ejercicio22.buscar(tfNombre.getText());
                    tfLugar.setText( Ejercicio22.lugar());
                    tfFecha.setText( Ejercicio22.fecha());
                    tfHoraFin.setText(Ejercicio22.horaI());
                    tfHoraInicio.setText(Ejercicio22.horaF());
                    tfAforo.setText(Ejercicio22.aforo());
                    break;
                case 'a':
                    Ejercicio22.buscar(tfNombre.getText());
                    tfLugar.setText( Ejercicio22.lugar());
                    tfFecha.setText( Ejercicio22.fecha());
                    tfHoraFin.setText(Ejercicio22.horaI());
                    tfHoraInicio.setText(Ejercicio22.horaF());
                    tfAforo.setText(Ejercicio22.aforo());
                    tfLugar.setEnabled(true);
                    tfFecha.setEnabled(true);
                    tfHoraFin.setEnabled(true);
                    tfHoraInicio.setEnabled(true);
                    tfAforo.setEnabled(true);
                    tfNombre.setEnabled(false); 
                    bConfirmar.setEnabled(false); 
                    break;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se encuentra el evento");
        }
    }//GEN-LAST:event_bConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfAforo;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfHoraFin;
    private javax.swing.JTextField tfHoraInicio;
    private javax.swing.JTextField tfLugar;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
